New Language Support: Move on Aptos
semgrep/ocaml-tree-sitter-semgrep pull request #482
Opened 2024-06-06 23:48 UTC by ArArgon

This PR adds support for the move language with Aptos flavor.

aptos-core: https://github.com/aptos-labs/aptos-core
Tree-sitter parser: https://github.com/aptos-labs/tree-sitter-move-on-aptos

The tree-sitter parser adopts Apache 2.0 license.

### Security

- [ ] Change has no security implications (otherwise, ping the security team)

2024-06-06 23:49 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/semgrep/ocaml-tree-sitter-semgrep?pullRequest=482) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/semgrep/ocaml-tree-sitter-semgrep?pullRequest=482) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/semgrep/ocaml-tree-sitter-semgrep?pullRequest=482) it.</sub>

2024-06-07 11:03 UTC, aryx commented
We need the CLA to move forward. Note that the CLA does not concern the code in the tree-sitter-move-on-aptos module; it's just about the changes in the ocaml-tree-sitter-semgrep (and later semgrep) repository.

2024-06-07 11:04 UTC, aryx commented
Would be good to add a few tests in lang/semgrep-grammars/src/semgrep-move-on-aptos/test/corpus/semgrep.txt
You can follow what the other did for the other languages and imitate.

2024-06-07 11:04 UTC, aryx approved these changes
LGTM. We just need the CLA and few corpus tests and we can merge this.

2024-06-07 11:05 UTC, aryx requested changes
request change just for those 2 things. Once done I can merge.

2024-06-07 16:40 UTC, ArArgon commented
> LGTM. We just need the CLA and few corpus tests and we can merge this.

@aryx 
We are waiting for our legal team to give us a feedback. Once they approved, I will fill out the CLA. In the meantime, I will add some corpus tests.

Besides, what is the next step after merging this PR? When I ran `./release X --dry-run`, it suggested there should be a `semgrep-move-on-aptos` repo. 'How to add support for a new language' is out of date since section 'Publishing generated parsers', too.

2024-06-07 16:52 UTC, aryx commented
yes this part it needs to be done at first by someone from semgrep
we need to create this empty repo.

2024-06-07 16:54 UTC, aryx commented
created here: https://github.com/semgrep/semgrep-move-on-aptos

2024-06-08 10:44 UTC, aryx approved these changes

2024-06-08 10:44 UTC, merged

2024-06-08 10:51 UTC, aryx commented
ok I've run ./release move-on-aptos and as you can see here: https://github.com/semgrep/semgrep-move-on-aptos
the C and OCaml code to parse Move is now accessible in this repository.
We now need to include this repo as a submodule in the semgrep repo and write the glue so it can be used in semgrep.