Upgrade C# grammar
semgrep/ocaml-tree-sitter-semgrep pull request #490
Opened 2024-07-02 01:18 UTC by mjambon

This uses the latest version of tree-sitter-c-sharp and updates the grammar extension for semgrep. `tree-sitter generate` still takes more than 16GB of RAM :-(

### Security

- [ ] Change has no security implications (otherwise, ping the security team)

2024-07-02 03:50 UTC, brandonspark approved these changes

2024-07-02 03:59 UTC, DrewDennison approved these changes

2024-07-02 10:26 UTC, aryx requested changes
I get conflicts and test regressions with this PR (I'm able to run tree-sitter on my 32GB machine).

2024-07-10 11:34 UTC, aryx commented
probably better to restart from scratch since I've made an intermediate PR that update also to a more recent tree-sitter-csharp (but not the latest one).

2024-07-10 11:34 UTC, closed without merging