Add Move support for semgrep
semgrep/ocaml-tree-sitter-semgrep pull request #500
Opened 2024-07-25 18:35 UTC by chargarlic

### Security

- [ ] Change has no security implications (otherwise, ping the security team)

2024-07-25 18:35 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/semgrep/ocaml-tree-sitter-semgrep?pullRequest=500) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/semgrep/ocaml-tree-sitter-semgrep?pullRequest=500) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/semgrep/ocaml-tree-sitter-semgrep?pullRequest=500) it.</sub>

2024-07-25 19:29 UTC, ihji commented
LGTM. Is the update to the `tree-sitter-c-sharp` submodule needed for this PR?

2024-07-26 08:17 UTC, aryx commented
yes please remove the change related to tree-sitter-csharp.

2024-07-26 08:18 UTC, aryx requested changes
remove the c# change.
Also could you sign the CLA and explain a little bit in the PR description
what is the difference between this Move and the Move on aptos we already have?
Should we rename it to move-on-sui?

2024-07-26 17:05 UTC, chargarlic commented
> LGTM. Is the update to the `tree-sitter-c-sharp` submodule needed for this PR?

No it is not, i cleared it up and removed those now

2024-07-26 17:06 UTC, chargarlic commented
> remove the c# change. Also could you sign the CLA and explain a little bit in the PR description what is the difference between this Move and the Move on aptos we already have? Should we rename it to move-on-sui?

There are feature and syntax differences, i can rename to move-on-sui

2024-07-29 14:19 UTC, aryx approved these changes

2024-07-29 14:19 UTC, merged

2024-07-29 14:25 UTC, aryx reviewed
I'm fixing this in another PR

2024-07-29 14:25 UTC, aryx commented on lang/semgrep-grammars/src/semgrep-move-on-sui/grammar.js
> +  name: 'move',
this needed to be move_on_sui, otherwise
./test-lang move-on-sui was failing with an OCaml linking error.

2024-07-29 14:26 UTC, aryx commented
Fix here: https://github.com/semgrep/ocaml-tree-sitter-semgrep/pull/501

2024-07-29 17:37 UTC, aryx commented
ok I've generated the code in https://github.com/semgrep/semgrep-move-on-sui

2024-07-29 17:37 UTC, aryx commented
now you need to add this repo as a submodule in the semgrep repo and start to add the language in semgrep-interface like the other person did for Move-on-aptos.