Circom grammar update
semgrep/ocaml-tree-sitter-semgrep pull request #511
Opened 2024-09-18 15:31 UTC by Frodan

Updating tree-sitter and semgrep grammar for circom language.

2024-09-18 16:24 UTC, aryx commented
@mjambon is in the middle of a big refactoring in ocaml-tree-sitter-semgrep but once his PR is merged we can probably merge this one.

2024-09-23 08:52 UTC, aryx commented
@mjambon can we merge this? Are you done with your tree-sitter version refactoring?

2024-09-30 06:53 UTC, Frodan commented
Hi, any updates on merging this?

2024-10-09 17:05 UTC, aryx requested changes
Sorry for the late review, we had an offsite last week.
Can you add some test corpus for those new supported constructs?
Also was it possible instead to modify  the original grammar so that
we don't have to copy so much from main_component_definition and component_declaration?
like if you introduce an intermediate rule for what is after the =, like main_component_value, then it's possible to override just that.

2025-04-24 19:27 UTC, nmote commented
This looks to be abandoned. Feel free to open a new PR (or reopen this one if that's possible) if you'd still like to contribute.

2025-04-24 19:27 UTC, closed without merging